# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'epicworld.ui'
#
# Created: Wed Dec 11 20:41:31 2013
#      by: PyQt5 UI code generator 5.0.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 608)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainCanvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.mainCanvas.setObjectName("mainCanvas")
        self.horizontalLayout.addWidget(self.mainCanvas)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.bodyListDock = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyListDock.sizePolicy().hasHeightForWidth())
        self.bodyListDock.setSizePolicy(sizePolicy)
        self.bodyListDock.setMinimumSize(QtCore.QSize(70, 121))
        self.bodyListDock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.bodyListDock.setObjectName("bodyListDock")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bodyList = QtWidgets.QListView(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyList.sizePolicy().hasHeightForWidth())
        self.bodyList.setSizePolicy(sizePolicy)
        self.bodyList.setObjectName("bodyList")
        self.verticalLayout.addWidget(self.bodyList)
        self.bodyListDock.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.bodyListDock)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.propertiesDock = QtWidgets.QDockWidget(MainWindow)
        self.propertiesDock.setEnabled(False)
        self.propertiesDock.setMinimumSize(QtCore.QSize(207, 308))
        self.propertiesDock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.propertiesDock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.propertiesDock.setObjectName("propertiesDock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.idGroup = QtWidgets.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idGroup.sizePolicy().hasHeightForWidth())
        self.idGroup.setSizePolicy(sizePolicy)
        self.idGroup.setObjectName("idGroup")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.idGroup)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.idEdit = QtWidgets.QLineEdit(self.idGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idEdit.sizePolicy().hasHeightForWidth())
        self.idEdit.setSizePolicy(sizePolicy)
        self.idEdit.setObjectName("idEdit")
        self.horizontalLayout_6.addWidget(self.idEdit)
        self.verticalLayout_2.addWidget(self.idGroup)
        self.widthGroup = QtWidgets.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthGroup.sizePolicy().hasHeightForWidth())
        self.widthGroup.setSizePolicy(sizePolicy)
        self.widthGroup.setObjectName("widthGroup")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widthGroup)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widthEdit = QtWidgets.QLineEdit(self.widthGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthEdit.sizePolicy().hasHeightForWidth())
        self.widthEdit.setSizePolicy(sizePolicy)
        self.widthEdit.setObjectName("widthEdit")
        self.horizontalLayout_5.addWidget(self.widthEdit)
        self.verticalLayout_2.addWidget(self.widthGroup)
        self.posGroup = QtWidgets.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posGroup.sizePolicy().hasHeightForWidth())
        self.posGroup.setSizePolicy(sizePolicy)
        self.posGroup.setObjectName("posGroup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.posGroup)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.yEdit = QtWidgets.QLineEdit(self.posGroup)
        self.yEdit.setObjectName("yEdit")
        self.gridLayout.addWidget(self.yEdit, 1, 2, 1, 1)
        self.xEdit = QtWidgets.QLineEdit(self.posGroup)
        self.xEdit.setObjectName("xEdit")
        self.gridLayout.addWidget(self.xEdit, 0, 2, 1, 1)
        self.labelX = QtWidgets.QLabel(self.posGroup)
        self.labelX.setObjectName("labelX")
        self.gridLayout.addWidget(self.labelX, 0, 0, 1, 1)
        self.labelY = QtWidgets.QLabel(self.posGroup)
        self.labelY.setObjectName("labelY")
        self.gridLayout.addWidget(self.labelY, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.posGroup)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.propertiesDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.propertiesDock)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionImport_Bodies = QtWidgets.QAction(MainWindow)
        self.actionImport_Bodies.setCheckable(False)
        self.actionImport_Bodies.setObjectName("actionImport_Bodies")
        self.actionDelete_Body = QtWidgets.QAction(MainWindow)
        self.actionDelete_Body.setCheckable(False)
        self.actionDelete_Body.setObjectName("actionDelete_Body")
        self.actionScale = QtWidgets.QAction(MainWindow)
        self.actionScale.setCheckable(False)
        self.actionScale.setObjectName("actionScale")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionRaise = QtWidgets.QAction(MainWindow)
        self.actionRaise.setObjectName("actionRaise")
        self.actionLower = QtWidgets.QAction(MainWindow)
        self.actionLower.setObjectName("actionLower")
        self.actionDuplicate = QtWidgets.QAction(MainWindow)
        self.actionDuplicate.setObjectName("actionDuplicate")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionImport_Bodies)
        self.menuAction.addAction(self.actionDelete_Body)
        self.menuAction.addAction(self.actionScale)
        self.menuAction.addAction(self.actionUndo)
        self.menuAction.addAction(self.actionRedo)
        self.menuAction.addAction(self.actionRaise)
        self.menuAction.addAction(self.actionLower)
        self.menuAction.addAction(self.actionDuplicate)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())
        self.toolBar.addAction(self.actionDelete_Body)
        self.toolBar.addAction(self.actionScale)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionRaise)
        self.toolBar.addAction(self.actionLower)
        self.toolBar.addAction(self.actionDuplicate)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Epic World"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAction.setTitle(_translate("MainWindow", "Action"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.idGroup.setTitle(_translate("MainWindow", "id"))
        self.widthGroup.setTitle(_translate("MainWindow", "Width"))
        self.posGroup.setTitle(_translate("MainWindow", "Position"))
        self.labelX.setText(_translate("MainWindow", "x"))
        self.labelY.setText(_translate("MainWindow", "y"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionImport_Bodies.setText(_translate("MainWindow", "Import bodies From Physics Body Editor"))
        self.actionImport_Bodies.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionDelete_Body.setText(_translate("MainWindow", "Delete"))
        self.actionDelete_Body.setShortcut(_translate("MainWindow", "Del"))
        self.actionScale.setText(_translate("MainWindow", "Scale"))
        self.actionScale.setShortcut(_translate("MainWindow", "Space"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionRaise.setText(_translate("MainWindow", "Raise"))
        self.actionRaise.setShortcut(_translate("MainWindow", "Ctrl+."))
        self.actionLower.setText(_translate("MainWindow", "Lower"))
        self.actionLower.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionDuplicate.setText(_translate("MainWindow", "Duplicate"))
        self.actionDuplicate.setShortcut(_translate("MainWindow", "Ctrl+D"))

